import ANALITIC from "@/app/assets/icons/analytic.svg";
import ARROWDOWN from "@/app/assets/icons/arrow-down.svg";
import ARROWLEFT from "@/app/assets/icons/arrow-left.svg";
import ARROWRIGHT from "@/app/assets/icons/arrow-right.svg";
import ARROWUP from "@/app/assets/icons/arrow-up.svg";
import AUDIT from "@/app/assets/icons/audit.svg";
import AUTHOR from "@/app/assets/icons/author.svg";
import BRIEFCASE from "@/app/assets/icons/briefcase.svg";
import CHARTDECREASE from "@/app/assets/icons/chart-decrease.svg";
import CALENDAR from "@/app/assets/icons/calendar.svg";
import CHAT from "@/app/assets/icons/chat.svg";
import CHECK from "@/app/assets/icons/check.svg";
import CILT from "@/app/assets/icons/cilt.svg";
import CITY from "@/app/assets/icons/city.svg";
import CLIMATE from "@/app/assets/icons/climate.svg";
import COMPUTER from "@/app/assets/icons/computer.svg";
import COPY from "@/app/assets/icons/copy.svg";
import DASHBOARD from "@/app/assets/icons/dashboard.svg";
import DOWN from "@/app/assets/icons/down.svg";
import DOWNLOAD from "@/app/assets/icons/download.svg";
import EMAIL from "@/app/assets/icons/email.svg";
import ERROR from "@/app/assets/icons/error.svg";
import EYE from "@/app/assets/icons/eye.svg";
import FACEBOOK from "@/app/assets/icons/facebook/Default.svg";
import FOCUS from "@/app/assets/icons/focus.svg";
import HOME from "@/app/assets/icons/home.svg";
import IDCARD from "@/app/assets/icons/id-card.svg";
import INFO from "@/app/assets/icons/info.svg";
import KURUL from "@/app/assets/icons/kurul.svg";
import LOCATION from "@/app/assets/icons/location.svg";
import LEFTCROSS from "@/app/assets/icons/left-cross.svg";
import LEFT from "@/app/assets/icons/left.svg";
import LINK from "@/app/assets/icons/link.svg";
import LINKEDIN from "@/app/assets/icons/linkedin.svg";
import MASKGROUP1 from "@/app/assets/icons/mask-group-1.svg";
import MENU from "@/app/assets/icons/menu.svg";
import MESSAGE from "@/app/assets/icons/message.svg";
import MOBILEBANKING from "@/app/assets/icons/mobile-banking.svg";
import MULTIMEDIAPLAYER from "@/app/assets/icons/multimedia-player.svg";
import NATURE from "@/app/assets/icons/nature.svg";
import NUMBER from "@/app/assets/icons/number.svg";
import PDF from "@/app/assets/icons/pdf.svg";
import PENCILRULER from "@/app/assets/icons/pencil-ruler.svg";
import PHONE from "@/app/assets/icons/phone.svg";
import PIECHART from "@/app/assets/icons/pie-chart.svg";
import PRESENTATION from "@/app/assets/icons/presentation.svg";
import PROMOTION from "@/app/assets/icons/promotion.svg";
import RIGHTCROSS from "@/app/assets/icons/right-cross.svg";
import RIGHT from "@/app/assets/icons/right.svg";
import ROADMAPLOCATION from "@/app/assets/icons/roadmap-location.svg";
import SEARCH from "@/app/assets/icons/search.svg";
import SEARCHFILE from "@/app/assets/icons/search-file.svg";
import SHOPPINGLIST from "@/app/assets/icons/shopping-list.svg";
import STAMP from "@/app/assets/icons/stamp.svg";
import STAPLER from "@/app/assets/icons/stapler.svg";
import STATS from "@/app/assets/icons/stats.svg";
import STICKYNOTES from "@/app/assets/icons/sticky-notes.svg";
import TABLELAMP from "@/app/assets/icons/table-lamp.svg";
import TAPE from "@/app/assets/icons/tape.svg";
import TARGET from "@/app/assets/icons/target.svg";
import THROPHY from "@/app/assets/icons/throphy.svg";
import TRANSACTION from "@/app/assets/icons/transaction.svg";
import UP from "@/app/assets/icons/up.svg";
import UPLOAD from "@/app/assets/icons/upload.svg";
import VECTOR from "@/app/assets/icons/vector.svg";
import WARNING from "@/app/assets/icons/warning.svg";
import WORLD from "@/app/assets/icons/world.svg";

export const ANALITICSVG = <ANALITIC />;
export const ARROWDOWNSVG = <ARROWDOWN />;
export const ARROWLEFTSVG = <ARROWLEFT />;
export const ARROWRIGHTSVG = <ARROWRIGHT />;
export const ARROWUPSVG = <ARROWUP />;
export const AUDITSVG = <AUDIT />;
export const AUTHORSVG = <AUTHOR />;
export const BRIEFCASESVG = <BRIEFCASE />;
export const CALENDARSVG = <CALENDAR />;
export const CHARTDECREASESVG = <CHARTDECREASE />;
export const CHATSVG = <CHAT />;
export const CHECKSVG = <CHECK />;
export const CILTSVG = <CILT />;
export const CITYSVG = <CITY />;
export const CLIMATESVG = <CLIMATE />;
export const COMPUTERSVG = <COMPUTER />;
export const COPYSVG = <COPY />;
export const DASHBOARDSVG = <DASHBOARD />;
export const DOWNSVG = <DOWN />;
export const DOWNLOADSVG = <DOWNLOAD />;
export const EMAILSVG = <EMAIL />;
export const ERRORSVG = <ERROR />;
export const EYESVG = <EYE />;
export const FACEBOOKSVG = <FACEBOOK />;
export const FOCUSSVG = <FOCUS />;
export const HOMESVG = <HOME />;
export const IDCARDSVG = <IDCARD />;
export const INFOSVG = <INFO />;
export const KURULSVG = <KURUL />;
export const LOCATIONSVG = <LOCATION />;
export const LEFTCROSSSVG = <LEFTCROSS />;
export const LEFTSVG = <LEFT />;
export const LINKSVG = <LINK />;
export const LINKEDINSVG = <LINKEDIN />;
export const MASKGROUP1SVG = <MASKGROUP1 />;
export const MENUSVG = <MENU />;
export const MESSAGESVG = <MESSAGE />;
export const MOBILEBANKINGSVG = <MOBILEBANKING />;
export const MULTIMEDIAPLAYERSVG = <MULTIMEDIAPLAYER />;
export const NATURESVG = <NATURE />;
export const NUMBERSVG = <NUMBER />;
export const PDFSVG = <PDF />;
export const PENCILRULERSVG = <PENCILRULER />;
export const PHONESVG = <PHONE />;
export const PIECHARTSVG = <PIECHART />;
export const PRESENTATIONSVG = <PRESENTATION />;
export const PROMOTIONSVG = <PROMOTION />;
export const RIGHTCROSSSVG = <RIGHTCROSS />;
export const RIGHTSVG = <RIGHT />;
export const ROADMAPLOCATIONSVG = <ROADMAPLOCATION />;
export const SEARCHSVG = <SEARCH />;
export const SEARCHFILESVG = <SEARCHFILE />;
export const SHOPPINGLISTSVG = <SHOPPINGLIST />;
export const STAMPSVG = <STAMP />;
export const STAPLERSVG = <STAPLER />;
export const STATSSVG = <STATS />;
export const STICKYNOTESSVG = <STICKYNOTES />;
export const TABLELAMPSVG = <TABLELAMP />;
export const TAPESVG = <TAPE />;
export const TARGETSVG = <TARGET />;
export const THROPHYSVG = <THROPHY />;
export const TRANSACTIONSVG = <TRANSACTION />;
export const UPSVG = <UP />;
export const UPLOADSVG = <UPLOAD />;
export const VECTORSVG = <VECTOR />;
export const WARNINGSVG = <WARNING />;
export const WORLDSVG = <WORLD />;
